words = [
    "barbie", "rocker", "diamond", "leet", "beer", "rockstar", "bulleit", "moon", "draught", "tanaka", "yankee",
    "aviator", "queen", "cocktail", "absolute", "mountain", "light", "yankee", "beef", "able", "bad", "best", "better",
    "big", "black", "certain", "clear", "different", "early", "easy", "economic", "federal", "free", "full", "good",
    "great", "hard", "high", "human", "important", "international", "large", "late", "little", "local", "long", "low",
    "major", "military", "national", "new", "old", "only", "other", "political", "possible", "public", "real", "recent",
    "right", "small", "social", "special", "strong", "sure", "true", "white", "whole", "not", "also", "very", "often",
    "however", "too", "usually", "really", "early", "never", "always", "sometimes", "together", "likely", "simply",
    "generally", "instead", "actually", "again", "rather", "almost", "especially", "ever", "quickly", "probably",
    "already", "below", "directly", "therefore", "else", "thus", "easily", "eventually", "exactly", "certainly",
    "normally", "currently", "extremely", "finally", "constantly", "properly", "soon", "specifically", "ahead", "daily",
    "highly", "immediately", "relatively", "slowly", "fairly", "primarily", "completely", "ultimately", "widely",
    "recently", "seriously", "frequently", "fully", "mostly", "naturally", "nearly", "occasionally", "carefully",
    "clearly", "essentially", "possibly", "slightly", "somewhat", "equally", "greatly", "necessarily", "personally",
    "rarely", "regularly", "similarly", "basically", "closely", "effectively", "initially", "literally", "mainly",
    "merely", "gently", "hopefully", "originally", "roughly", "significantly", "totally", "twice", "elsewhere",
    "everywhere", "obviously", "perfectly", "physically", "successfully", "suddenly", "truly", "virtually",
    "altogether", "anyway", "automatically", "deeply", "definitely", "deliberately", "hardly", "readily", "terribly",
    "unfortunately", "forth", "briefly", "moreover", "strongly", "honestly", "previously", "as", "there", "when", "how",
    "so", "up", "out", "no", "only", "well", "then", "first", "where", "why", "now", "around", "once", "down", "off",
    "here", "tonight", "away", "today", "far", "quite", "later", "above", "yet", "maybe", "otherwise", "near",
    "forward", "somewhere", "anywhere", "please", "forever", "somehow", "absolutely", "abroad", "yeah", "nowhere",
    "tomorrow", "yesterday", "the", "to", "in", "on", "by", "more", "about", "such", "through", "new", "just", "any",
    "each", "much", "before", "between", "free", "right", "best", "since", "both", "sure", "without", "back", "better",
    "enough", "lot", "small", "though", "less", "little", "under", "next", "hard", "real", "left", "least", "short",
    "last", "within", "along", "lower", "true", "bad", "across", "clear", "easy", "full", "close", "late", "proper",
    "fast", "wide", "item", "wrong", "ago", "behind", "quick", "straight", "direct", "extra", "morning", "pretty",
    "overall", "alone", "bright", "flat", "whatever", "slow", "clean", "fresh", "whenever", "cheap", "thin", "cool",
    "fair", "fine", "smooth", "false", "thick", "collect", "nearby", "wild", "apart", "none", "strange", "tourist",
    "aside", "loud", "super", "tight", "gross", "ill", "downtown", "honest", "ok", "pray", "weekly", "ask", "be",
    "become", "begin", "call", "can", "come", "could", "do", "feel", "find", "get", "give", "go", "have", "hear",
    "help", "keep", "know", "leave", "let", "like", "live", "look", "make", "may", "mean", "might", "move", "need",
    "play", "put", "run", "say", "see", "seem", "should", "show", "start", "take", "talk", "tell", "think", "try",
    "turn", "use", "want", "will", "work"
         ]